### PR TITLE
Tagged literal support

### PR DESCRIPTION
**Pull request by matter123**
Implements #236.

This PR adds a generic way of supporting tagged raw string literals. Currently, only regex patterns are supported. The regex grammar comes from embedding MagicPython's regex grammar.

raw_string literals were moved to a separate file to be able to support many different types of tagged literals without cluttering the main grammar.

Example Image:
Screenshot from 2019-07-11 01-30-52

### CODE REVIEW

**Comment by matter123** [comment]
With the tests passing, I'm removing the WIP status.

**Comment by matter123** [comment]
When #295 is merged in, we should make a copy of magic pythons regexp and add an early bailout pattern of `/(?=\)(?:_r|re|regex)")/`

That should prevent the issue described in https://github.com/MagicStack/MagicPython/issues/27#issuecomment-155483716 which is present with the PR as well.

**Comment by matter123** [comment]
Based on https://github.com/microsoft/vscode/issues/1751#issuecomment-414877322
support for SQL has been added.
Screenshot from 2019-07-15 19-17-12

**Comment by jeff-hykin** [comment]
So does this require that the string start with "re" for it to be regex and the string start with "SQL" to be sql?

**Comment by matter123** [comment]
For regex: _r, re, regex
For sql: SQL, PSQL

**Comment by jeff-hykin** [comment]
Wouldn't that mess up the regex pattern though?
Here's an example from https://solarianprogrammer.com/2011/10/16/cpp-11-raw-strings-literals-tutorial/
```
string input;
regex rr(R"(((\+|-)?[[:digit:]]+)(\.(([[:digit:]]+)?))?((e|E)((\+|-)?)[[:digit:]]+)?)");
cout << "Give me a real number!" << endl;
cin >> input;
if ( regex_match(input,rr) )  {
        cout<<"float"<<endl;
} else {
    cout<<"Invalid input"<<endl;
}
```

**Comment by matter123** [comment]
Yes, that would not get syntax highlighting because it's not tagged. As discussed in #236 tagging of generic raw strings requires support from vscode.

**Comment by jeff-hykin** [comment]
Wow, I need to do a better job of reading. Thanks for this feature 👍

**Pull request merged**
