### PR TITLE
add suport for enum definitions

### PR DESCRIPTION
**Pull request by matter123**
This PR tags `a` and `b` in the following code snippet.
```c++
enum A {
a, b
};
```
`a` and `b` are tagged as `constant.other.enum` though arguments could be made for other scopes.
Enum values are constant, but it may be advantageous to mark them as variables, as anywhere else they will be treated as such. Additionally `const int some_constant` is still marked as a variable.

Language | Scope
----------|-------
java | `constant.other.enum.java`
c# | `entity.name.variable.enum-member.cs`
typescript | `variable.other.enummember.ts`

### CODE REVIEW

**Comment by jeff-hykin** [comment]
Man I wish the new tagging standard was ready. There is no prefect fix for this. Entity isn't great because textmate conventions say "an entity refers to a larger part of the document, for example a chapter, class, function, or tag."
https://macromates.com/manual/en/language_grammars#naming_conventions

I think marking them as a variable is pretty accurate. C++ has the idea of a "constant variable" even though that phrase is a contradiction. I believe the technical definition of a C++ variable is "a named location in memory". And since, I'm pretty sure, the enum is stored in memory, it's accurate.

**Comment by matter123** [comment]
enum variables are adressable but not enum values;
```c++
enum A {
a, b
};
cout << &A::a;
```
does not compile.

**Comment by jeff-hykin** [comment]
Oh that's interesting. Well, in terms of practicality, it would probably be best to mark them as variables since that is probably what they will be marked as in other places of the code.

**Comment by jeff-hykin** [comment]
I guess `variable.other.enummember` is probably the best solution since it is already in use and will fit the most with the other variables in the code.

**Comment by jeff-hykin** [comment]
```
enum A {
a, b
};
```
Adding a space after the `{` breaks the highlighting. This might be a problem with the block finder.

**Comment by matter123** [comment]
Yeah, that is a duplicate of #143 and #132. see https://github.com/jeff-hykin/cpp-textmate-grammar/issues/132#issuecomment-489208354

**Pull request merged**
