### PR TITLE
Add type alias

### PR DESCRIPTION
**Pull request by matter123**
Adds a `type_alias` pattern and tests. Extracted from #135.

### CODE REVIEW

**Comment by jeff-hykin** [comment]
If you can add some unit tests to `:type_alias`, I'll go ahead and merge it in.

I still don't fully understand the `:qualified_type` pattern but I'll figure it out later

**Comment by matter123** [comment]
Sure.

**Comment by matter123** [comment]
The unit tests aren't quite sufficient yet

**Comment by matter123** [comment]
So `:qualified_type` is supposed to match a fully storage, namespace, and template qualified type.
that is `struct A::B::C::D` or `std::enable_if<std::numeric_limit<long long int>::digits > 10, bool>` It doesn't match type qualifiers like const or static or restrict, or type modifiers like `**` and `&` so that it can be used in more places. The hope/plan is that much in the same way `variable_name` is used anywhere a name is expected, `qualified_type` is used whenever a type is expected.

**Pull request merged**
