### PR TITLE
Fix colon in enums #55

### PR DESCRIPTION
**Pull request by matter123**
enums are sufficiently different to deserve their own pattern separate from the class/struct/union pattern.
This PR does so and provides better scopes.

### CODE REVIEW

**Comment by jeff-hykin** [comment]
I manually merged this one since there with conflicts caused by renaming and moving all of the files for #48 

I put the changes on this branch if you can take a look at them. They're already on master, but I'll hold of on publishing the extension until you think the changes are good.

**Comment by matter123** [comment]
regressions:
 - anonymous structs are no longer tagged as `storage.type.struct`
 -     #ifdef __cplusplus
       extern "C" {
       #endif
is marked `invalid.illegal.stray-endif.cpp`

Overall fairly nice however

**Comment by matter123** [comment]
Once this is corrected Ill redo #54.

**Comment by jeff-hykin** [comment]
I believe this also had the problem before this:
```
#ifdef __cplusplus
class thing {
#endif
```
I got rid of the `invalid.illegal.stray`, but it meant the #endif is untagged. So I made a hacky fix for that since its part of the bigger issue of C++ if-directives in general

**Pull request closed without merging**
