### PR TITLE
Fix for #415

### PR DESCRIPTION
**Pull request by matter123**
The performance issue can be dramatically
reduced by making std_space in its entirety  atomic.

This is not a complete fix.

All tests pass

### CODE REVIEW

**Comment by matter123** [comment]
With the second set of fixes, perf reports just under 8 seconds to parse 888 copies of the bad text.

@maroc81 was it just the one line that was causing an issue?

**Comment by maroc81** [comment]
We have about a half dozen header files generated from a tool with formatting similar to that bad line that suffer from this problem.  In my testing, it appears to be caused by very long text between parenthesis.

I was just able to reproduce with a different line you can try:

`int main(void /* insert 2000 spaces here*/)`

Duplicate that line a 100 times or so and you should see the same behavior.

**Comment by matter123** [comment]
@maroc81 Thanks, after replacing `DEFINE_THING((` with `int main(void)` and `))` with `)` my 800 line sample file parses in 4.7s.

**Comment by maroc81** [comment]
Thanks @matter123 !

**Comment by jeff-hykin** [comment]
If you're confident this won't cause side effects, go ahead a merge. It'll be tomorrow night before I get a chance to look at and publish

**Comment by matter123** [comment]
The only change that may cause an issue is the change of std_space from lazy to possessive. However, due to std_space being able to match nothing, I dont think its likely.

**Comment by jeff-hykin** [comment]
> The only change that may cause an issue is the change of std_space from lazy to possessive. However, due to std_space being able to match nothing, I dont think its likely.

Yeah I think thats a pretty safe bet. If that does cause something to fail I imagine that individual pattern is what would need the change.

Changes published with `1.14.14`

**Pull request merged**
