### PR TITLE
Prevent a number from starting a lambda capture

### PR DESCRIPTION
**Pull request by matter123**
Fixes: #412
Related: microsoft/vscode#85385

### CODE REVIEW

**Comment by matter123** [comment]
@valentjn

This latest commit prohibits `;` or `]` (in addition to the previously added `[` from following a lambada capture.

Screen Shot 2019-11-25 at 08 47 37

**Comment by matter123** [comment]
Closing as resolved in v1.14.15

**Comment by valentjn** [comment]
@matter123 I don't think this is resolved. I just tested it with v1.14.16 and it only seems to resolve it when there's a number in the square brackets, not letters.

Screenshots of the above example - without Better C++ Syntax (VS Code 1.41.0, Linux x64):
Screenshot_20191230_094355

With Better C++ Syntax v1.14.16:
Screenshot_20191230_094316

The comment on line 3 is formatted correctly, but not the comment on line 10.

**Comment by matter123** [comment]
Thanks, didnt catch that.

**Comment by matter123** [comment]
Closing in favor of #437.

**Pull request closed without merging**
