### PR TITLE
WIP Fix #50

### LINKED ISSUE #50: [[attributes]] break syntax highlighting until `{`
Similar to #37 after a C++ attribute `[[fallthrough]]`,`[[nodiscard]]`, etc. Syntax highlighting breaks until `{`.

Example
```
switch(test) {
	case 1:
	break;
	case 2: [[fallthrough]];
	case 3: break; // no syntax highlighting
}
void func1();
[[noreturn]] void func2(/*syntax highlighting*/); // no syntax highlighting
struct st { // syntax highlighting works now
};
void func3();
```
Image:
Screenshot from 2019-04-01 19-53-11

### PR DESCRIPTION
**Pull request by matter123**
1.6.8 | #54 
-------|-----
Screenshot from 2019-04-07 19-37-46 | Screenshot from 2019-04-07 19-36-35

### CODE REVIEW

**Comment by matter123** [comment]
Code sample of interesting cases that I could find on cppreference.com and other places on the internet. https://gist.github.com/matter123/f0bf0fee6bd530892f7b7969466569b0

Currently, the following lines have issues
 - 10
 - 18
 - 30
 - 32
 - 42
 - 48
 - 54
 - 60
 - 62
 - 68
 - 69
 - 77
 - 90
 - 97
And the same for inside the namespace. namespaces no longer seem to affect attributes.

**Comment by jeff-hykin** [comment]
I'll try to take a look at all 3 of merge requests today and get them merged in

**Comment by matter123** [comment]
Ok I'll try to fix `[[fallthrough]]` fixed today.

**Comment by matter123** [comment]
With the latest commit all looks fine with the exception of lines 10 & 18. Both lines are of the format
`void foo[[attribute]]()` which while valid is most likely not very common.

**Comment by matter123** [comment]
The most recent commit changes the scope of the namespace in namespaced attributes. In example the `gnu` in `[[gnu::always_inline]]` has its scope changed from `entity.other.attribute.gnu.cpp` to `entity.name.namespace.cpp`.

This change is to make namespaces more consistent, in particular, scope-wise
`[[using gnu : always_inline]]` and `[[gnu::always_inline]]` now have the same scope for `gnu`.

**Comment by matter123** [comment]
Fixing lines 10 and 18 is dependant on https://github.com/jeff-hykin/cpp-textmate-grammar/projects/1#card-17467217. So this Pr is feature complete for now.

**Comment by jeff-hykin** [comment]
Sorry I wasn't able to finish this
 tonight. It looks like great work though.

**Comment by matter123** [comment]
Ok I'll try fixing line 59 then

**Comment by matter123** [comment]
#55 needs to be merged first, so that attributes can be added to enum types.

**Comment by matter123** [comment]
superseded by #69

**Pull request closed without merging**
