### PR TITLE
add alignas as an attribute type

### PR DESCRIPTION
**Pull request by matter123**
This fixes the `alignas` issue reported at https://github.com/jeff-hykin/cpp-textmate-grammar/issues/121#issuecomment-486286704.

There should probably be a refactor of inline_attribute soonish to support, support attributes like `PACKED` or `DLLEXPORT`

### CODE REVIEW

**Comment by jeff-hykin** [comment]
Are spaces allowed in `__declspec(`? like `__declspec    (`

**Comment by matter123** [comment]
Looks like yes https://godbolt.org/z/NqM5by

**Comment by jeff-hykin** [comment]
okay, then I think we should take it out of the representation, or we should make the representation a regex that matches it. I'll try to find the best way to incorporate that for the other similar things too.

I think it might be best to remove the `()`'s from the representation, and then just have the `function-like` adjective to indicate that it needs `()`'s in the pattern

**Comment by matter123** [comment]
Ok, the concern is with __attribute__(( as it has double parenthesis on both sides. e.g. `__attribute__((noreturn))` or `__attribute((constructor(101)))`

**Comment by jeff-hykin** [comment]
I went ahead an manually merged this in just now. I moved them out of tokens though so that we can change them to include spaces in the future.

**Pull request closed without merging**
