### PR TITLE
Number improvements

### PR DESCRIPTION
**Pull request by matter123**
From example.cpp
```c++
// invalid literals
1Ex
0xe+foo
0x1Px
// odd valid literals
0x'12345
0'12345
0x1Ex
1Px
```

Screenshot from 2019-04-23 17-45-34

This PR adds support for marking invalid numbers as `invalid.illegal.numeric.constant`, and for some slightly odd corner cases that were missed.

This PR unifies the C++ and C number handling. 

Edit:
`0xe+foo` is in fact invalid https://godbolt.org/z/CFM5V_ https://godbolt.org/z/P-ssZ1
and [[lex.pptoken]/4](http://eel.is/c++draft/lex#pptoken-4) (non normative):
> [ Example: The program fragment 0xe+foo is parsed as a preprocessing number token (one that is not a valid floating or integer literal token), even though a parse as three preprocessing tokens 0xe, +, and foo might produce a valid expression ...

though gcc suggest that operator""+foo would make the expression valid but that is not a valid ud-suffix

### CODE REVIEW

**Comment by matter123** [comment]
For reference with 1.8.7:
Screenshot from 2019-04-23 18-09-46

**Comment by jeff-hykin** [comment]
I might have to wait till this weekend to go over this and the alignas PR.

I like the extraction, thats probably the right way to go.

**Comment by matter123** [comment]
The number mentioned in https://github.com/jeff-hykin/cpp-textmate-grammar/pull/13#issuecomment-471094341 `0xAB.cdpfl` is not currently marked as invalid because `*_digits` are just greedy, not possessive. The regex engine backtracks and parses it as `0x`, `AB.c`, and a udl of `dpfL` but that is not [valid](https://godbolt.org/z/6sbdf5) the standard requires that hex_digits consume as many characters as possible before considering UDL's

**Comment by jeff-hykin** [comment]
What does `allow_udl` mean?

**Comment by matter123** [comment]
Probably could be a better name, but is a C++ number which have user-defined literals, or a C number which do not.

**Comment by jeff-hykin** [comment]
Oh okay 👍

**Comment by jeff-hykin** [comment]
This was a great change, I renamed some stuff and removed the need for the `grammar` object requirement. I'm a little bit concerned about mixing the C and C++ stuff, but I think its find for now.

**Comment by matter123** [comment]
This particular sharing should be okay as both C and C++ have the same grammar for `pp-number`
(C++ [[lex.ppnumber](http://eel.is/c++draft/lex.ppnumber)) (C11 N1570 A.1.9)

**Comment by jeff-hykin** [comment]
Screen Shot 2019-05-04 at 3 45 49 PM
Minor regression with this change

**Comment by jeff-hykin** [comment]
Fixed it by changing the pattern to
`start_pattern = lookBehindToAvoid(/\w/).lookAheadFor(/\d|\.\d/)`

But I think there's another minor issue
Screen Shot 2019-05-04 at 3 55 24 PM

**Comment by matter123** [comment]
No.
The first green is on an `integer_literal` where `f` is not an `integer_suffix`
The second green is on a `floating_literal` where `LL` is not a `floating_suffix`

**Comment by jeff-hykin** [comment]
okay great 👍 we should be all good then

**Comment by matter123** [comment]
So despite that a decimal point is needed for a number to be considered a floating constant [[lex.fcon]#fractional-constant](http://eel.is/c%2B%2Bdraft/lex.fcon#nt:fractional-constant). and `f` is not a integer-suffix [[lex.icon]#integer-suffix](http://eel.is/c%2B%2Bdraft/lex.icon#nt:integer-suffix). 
pretty much all compilers compile `auto a = 1e10f;` https://godbolt.org/z/X64wm4. Ill submit a PR fixing that.

**Pull request merged**
