### PR TITLE
Add script to generate duplicate grammars for embedding

### PR DESCRIPTION
**Pull request by matter123**
This PR is from the updated master.

`scripts/duplicateForEmbedding.js` adds a generic way to support any number of early bailout patterns.

~The grammar has been modified to use the macro embedded grammar for macros.~

### CODE REVIEW

**Comment by jeff-hykin** [comment]
This looks nice 👍 I'll work on getting it merged in in the next few days

**Comment by matter123** [comment]
The Extension Development Host scopes don't match what the tests say the scopes are. I'm guessing that I'm not announcing the syntax file correctly.

**Comment by matter123** [comment]
While this, might work and is probably still useful if another grammar needs to embed c++. This is not the best route to go with macros.

There are several disadvantages:
 - This duplicates non-range patterns
 - If an embeddable grammar is made it will need its own macro-fied version

**Comment by matter123** [comment]
If you prefer I can rewrite this in ruby, but otherwise, I believe it works well enough to be merged in.

**Comment by jeff-hykin** [comment]
> This looks nice 👍 I'll work on getting it merged in in the next few days

Oops 😬

**Comment by jeff-hykin** [comment]
I'll merge this in before I do anything else, but yeah in the future lets turn it into feature inside the ruby gem. I'm fine with stuff being done in javascript in general though, its basically the universal programming language.

I was imagining the bailed-out patterns as part of the language-syntax file, so you could take any subset language, for example regex, add an early bailout to it, and then use that like any other tag.

**Pull request merged**
