### PR TITLE
scope switch statements #110

### LINKED ISSUE #110: the colon of default case of switch missing parse.
image
maybe `punctuation.separator.default.cpp` useful.

### PR DESCRIPTION
**Pull request by matter123**
This fixes #110. `case` and `default` have been constrained to only match inside a switch statement.

### CODE REVIEW

**Comment by jeff-hykin** [comment]
I'll try to get both branched merged by tomorrow night. Sadly haven't had a chance to work on anything yet/

**Comment by peaceshi** [comment]
image
https://github.com/SDL-mirror/SDL/blob/master/src/video/windows/SDL_windowsevents.c#L88

**Comment by matter123** [comment]
@peaceshi That's with the C grammar, I'll create a separate issue.

**Comment by jeff-hykin** [comment]
I went ahead an manually merged this. I had to change it a bit to get all cases to work, adding `variableBounds[]` around the `switch`. The `()`'s were missing highlighting, I made them into a Range function and then had to modify `blockFinderFor` so that they would be matched even with no spaces (that part took forever). I'll wait to publish until you look over it though, the changes are in master.

I modified the way the grammar object works, and I'm using it now to import the switch statement into the c syntax. We can temporarily back-import until C++ is stable.

**Comment by matter123** [comment]
The changes to switch look good to me. The rest of the changes you made today look fine. Renaming some of the scopes should probably end up on the log due to #107, but I don't think Objective-C++ grabbed a specific c++ scope as Objective-C did for C.

**Comment by tristan957** [comment]
@peaceshi what are you doing in your comment to see the textmate grammar stuff?

**Comment by matter123** [comment]
@tristan957 Open the command Palette (ctrl-shift-P or cmd-shift-p) `Developer: Inspect TM Scopes`

**Comment by tristan957** [comment]
Ah thanks

**Pull request closed without merging**
